#!/usr/bin/env python3
"""Generate colors.toml and shell.toml from palette.toml.

The Ito-verse red used to be hand-written in three files that disagreed
(#a83859 in colors.toml, #ff2b4d in shell.toml, #6d1d1d in the QML modules).
This generator makes palette.toml the only place a color is ever chosen.

Every generated stop is contrast-checked against the ink background before it
is written, so a stop can never silently land in a role it cannot carry:

    paint stops fill shapes      - no contrast floor
    ui stops draw borders        - >= 3.0:1  (WCAG non-text)
    text stops carry glyphs      - >= 4.5:1  (WCAG normal text)

Usage:
    gen-palette.py --check          validate only, write nothing
    gen-palette.py --out DIR        generate into DIR (default: theme dir)
"""

import argparse
import colorsys
import sys
import tomllib
from pathlib import Path

THEME_DIR = Path(__file__).resolve().parent.parent / "themes" / "ito-verse"

# Minimum contrast each ramp stop must reach against the ink background.
CONTRAST_FLOOR = {
    "deep": None,
    "paint": None,
    "ui": 3.0,
    "focus": 3.0,
    "text": 4.5,
    "bright": 4.5,
}


def _linear(channel: int) -> float:
    c = channel / 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def luminance(hex_color: str) -> float:
    h = hex_color.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * _linear(r) + 0.7152 * _linear(g) + 0.0722 * _linear(b)


def contrast(a: str, b: str) -> float:
    la, lb = luminance(a), luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def hue_of(hex_color: str) -> float:
    h = hex_color.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    return colorsys.rgb_to_hls(r, g, b)[0]


def load(path: Path) -> dict:
    with path.open("rb") as fh:
        return tomllib.load(fh)


def validate(palette: dict) -> list[str]:
    """Return a list of problems. Empty list means the palette is sound."""
    problems = []
    ink = palette["base"]["ink"]
    blood = palette["blood"]

    if blood["paint"].lower() != blood["base"].lower():
        problems.append(
            f"blood.paint ({blood['paint']}) must equal blood.base ({blood['base']}): "
            "the anchor is the paint stop"
        )

    base_hue = hue_of(blood["base"])
    for stop, floor in CONTRAST_FLOOR.items():
        color = blood[stop]
        ratio = contrast(color, ink)

        # One hue for the whole ramp, or it stops reading as one family.
        drift = abs(hue_of(color) - base_hue) * 360
        drift = min(drift, 360 - drift)
        if drift > 6.0:
            problems.append(
                f"blood.{stop} ({color}) drifts {drift:.1f} deg from the base hue (max 6)"
            )

        if floor is not None and ratio < floor:
            problems.append(
                f"blood.{stop} ({color}) is {ratio:.2f}:1 on ink, needs >= {floor}:1"
            )
    return problems


def report(palette: dict) -> None:
    ink, bone = palette["base"]["ink"], palette["base"]["bone"]
    print(f"ink {ink}   bone {bone}   ({contrast(bone, ink):.2f}:1)\n")
    print(f"{'stop':<8}{'hex':<10}{'on ink':>9}{'bone on it':>13}   role floor")
    print("-" * 56)
    for stop, floor in CONTRAST_FLOOR.items():
        color = palette["blood"][stop]
        need = "paint (none)" if floor is None else f">= {floor}:1"
        print(
            f"{stop:<8}{color:<10}{contrast(color, ink):>8.2f}:1"
            f"{contrast(bone, color):>12.2f}:1   {need}"
        )


def render_colors_toml(p: dict) -> str:
    b, m, s, base = p["blood"], p["muted"], p["surfaces"], p["base"]
    return f"""# GENERATED by scripts/gen-palette.py from palette.toml - do not hand-edit.
# Ito-verse: ink + bone + blood. No pure #000/#FFF, no neons.
mode = "dark"

# Accent carries borders and small fills, so it sits on the ui stop.
accent = "{b['ui']}"
cursor = "{b['ui']}"

foreground = "{base['bone']}"
background = "{base['ink']}"

selection_foreground = "{s['light_fg']}"
selection_background = "{b['deep']}"

bg = "{base['ink']}"
lighter_bg = "{s['lighter_bg']}"
dark_bg = "{s['dark_bg']}"
darker_bg = "{s['darker_bg']}"

fg = "{base['bone']}"
light_fg = "{s['light_fg']}"
bright_fg = "{s['bright_fg']}"
dark_fg = "{s['dark_fg']}"
muted = "{s['muted_fg']}"
selection = "{b['deep']}"

# Only red is alive; everything else is muted warm gray.
# ANSI red is a TEXT role, so it uses the text stop, not the paint anchor.
red = "{b['text']}"
green = "{m['green']}"
yellow = "{m['yellow']}"
blue = "{m['blue']}"
magenta = "{m['magenta']}"
cyan = "{m['cyan']}"
orange = "{m['orange']}"
brown = "{m['brown']}"

bright_red = "{b['bright']}"
bright_green = "#8a9887"
bright_yellow = "#b3a586"
bright_blue = "#7d8fa0"
bright_magenta = "#9d7d8b"
bright_cyan = "#7d98a0"

color0 = "{base['ink']}"
color1 = "{b['text']}"
color2 = "{m['green']}"
color3 = "{m['yellow']}"
color4 = "{m['blue']}"
color5 = "{m['magenta']}"
color6 = "{m['cyan']}"
color7 = "{base['bone']}"

color8 = "{s['muted_fg']}"
color9 = "{b['bright']}"
color10 = "#8a9887"
color11 = "#b3a586"
color12 = "#7d8fa0"
color13 = "#9d7d8b"
color14 = "#7d98a0"
color15 = "{s['bright_fg']}"
"""


def render_shell_toml(p: dict) -> str:
    """Emit every shell surface, not just the bar.

    The engine falls back to colors.toml for any key a theme omits, which is
    why an Ito shell that only declared [bar] still looked generic everywhere
    else. Each surface below is assigned a ramp stop by its contrast role:
    borders and markers take ui/focus stops, error text takes the text stop,
    and only fills that sit under bone text are allowed the paint stop.
    """
    b, base, bar, st = p["blood"], p["base"], p["bar"], p["style"]
    ink, bone = base["ink"], base["bone"]
    deep, paint, ui, focus, text = (
        b["deep"], b["paint"], b["ui"], b["focus"], b["text"]
    )
    surfaces = p["surfaces"]

    return f"""# GENERATED by scripts/gen-palette.py from palette.toml - do not hand-edit.
# Ito-verse shell surfaces. Ink bar, bone text, blood actives.
#
# A theme that ships this file replaces the generated default outright, so every
# surface is declared here on purpose. Stops are assigned by contrast role; see
# palette.toml and run scripts/gen-palette.py --check to re-verify them.

[font]
base-size = {bar['font_base_size']}

[spacing]
scale = 1.0
scale-with-font = true

[bar]
background       = "{ink}"
background-alpha = {st['bar_alpha']}
text             = "{bone}"
active           = "{focus}"
scale-with-font  = true
size-horizontal  = {bar['size_horizontal']}
size-vertical    = {bar['size_vertical']}
icon-slot        = {bar['icon_slot']}
icon-canvas      = {bar['icon_canvas']}
icon-font        = {bar['icon_font']}
status-slot      = {bar['status_slot']}

[hyprland]
# Declared literally rather than tracking the Hyprland gradient: the border is
# part of the theme's identity, not of the window manager's current accent.
active-border            = "{ui}"
active-border-foreground = "{ui}"

[controls]
# Buttons, dropdowns and tab strips. Idle chrome stays bone so controls read as
# structure; only the persistent selected state earns blood.
normal-color        = "{bone}"
normal-fill-alpha   = {st['control_fill']}
normal-border       = "{bone}"
normal-border-width = 1
normal-border-alpha = {st['control_border']}

hover-cursor-color        = "{bone}"
hover-cursor-fill-alpha   = {st['control_hover_fill']}
hover-cursor-border       = "{ui}"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 0.55

focus-color        = "{bone}"
focus-fill-alpha   = {st['control_hover_fill']}
focus-border       = "{focus}"
focus-border-width = 1
focus-border-alpha = 0.75

selected-color        = "{bone}"
selected-fill-alpha   = 0.22
selected-border       = "{ui}"
selected-border-width = 1
selected-border-alpha = 1.0

pressed-fill-alpha   = 0.26
selection-fill-alpha = 0.38

[popups]
# Every bar flyout. Blood border is what ties the stock panels to the theme.
background       = "{ink}"
background-alpha = {st['popup_alpha']}
text             = "{bone}"
border           = "{ui}"
border-alpha     = 1.0
border-width     = {st['border_width']}

[tooltip]
# Tooltips are transient, so the border recedes to the deep stop.
background       = "{surfaces['dark_bg']}"
background-alpha = {st['tooltip_alpha']}
text             = "{bone}"
border           = "{deep}"
border-alpha     = 1.0

[notifications]
# Notifications interrupt, so they take the focus stop and a heavier border.
background       = "{ink}"
background-alpha = 1.0
text             = "{bone}"
border           = "{focus}"
border-alpha     = 1.0
border-width     = {st['border_width']}
countdown        = "{focus}"

[launcher]
background                = "{ink}"
background-alpha          = {st['card_alpha']}
text                      = "{bone}"
border                    = "{ui}"
border-alpha              = 1.0
scrim                     = "{surfaces['darker_bg']}"
scrim-alpha               = {st['scrim_alpha']}
selected-background       = "{paint}"
selected-background-alpha = {st['selected_fill']}
selected-text             = "{bone}"
selected-border           = "{focus}"
selected-border-alpha     = 0.85

[menu]
# Clipboard and emoji pickers inherit these. Selected rows are filled with the
# paint stop because bone on paint measures 8.28:1 - the anchor color finally
# gets to be a background instead of pretending to be text.
background                = "{ink}"
background-alpha          = 1.0
text                      = "{bone}"
border                    = "{ui}"
border-alpha              = 1.0
scrim                     = "{surfaces['darker_bg']}"
scrim-alpha               = {st['scrim_alpha']}
selected-background       = "{paint}"
selected-background-alpha = {st['selected_fill']}
selected-text             = "{bone}"
selected-border           = "{focus}"
selected-border-alpha     = 0.85

[polkit]
# Error text must stay readable under stress, so it takes the text stop.
background       = "{ink}"
background-alpha = 1.0
text             = "{bone}"
text-error       = "{text}"
border           = "{ui}"
border-error     = "{focus}"
border-alpha     = 1.0
scrim            = "{surfaces['darker_bg']}"
scrim-alpha      = {st['scrim_alpha']}
accent           = "{ui}"

[lock]
background       = "{ink}"
background-alpha = {st['lock_alpha']}
text             = "{bone}"
placeholder      = "{surfaces['muted_fg']}"
text-error       = "{text}"
border           = "{deep}"
border-active    = "{ui}"
border-error     = "{focus}"
border-alpha     = 1.0
selection        = "{paint}"
selection-alpha  = 0.55

[image-picker]
scrim                   = "{surfaces['darker_bg']}"
scrim-alpha             = {st['scrim_alpha']}
text                    = "{bone}"
selected-border         = "{focus}"
selected-border-alpha   = 1.0
unselected-border       = "{bone}"
unselected-border-alpha = {st['unselected_border']}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="validate only, write nothing")
    ap.add_argument("--out", type=Path, default=THEME_DIR, help="output directory")
    args = ap.parse_args()

    palette = load(THEME_DIR / "palette.toml")
    report(palette)

    problems = validate(palette)
    if problems:
        print("\nFAIL")
        for problem in problems:
            print(f"  - {problem}")
        return 1
    print("\nOK: every stop clears its role floor and holds the base hue.")

    if args.check:
        return 0

    args.out.mkdir(parents=True, exist_ok=True)
    for name, text in (
        ("colors.toml", render_colors_toml(palette)),
        ("shell.toml", render_shell_toml(palette)),
    ):
        target = args.out / name
        tmp = target.with_suffix(target.suffix + ".tmp")
        tmp.write_text(text, encoding="utf-8")
        assert tmp.read_text(encoding="utf-8") == text, f"readback mismatch for {name}"
        tmp.replace(target)
        print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
